import { useTheme } from "next-themes";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Logo from "../components/Logo";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { setTheme, resolvedTheme: currentTheme, theme } = useTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Fwiffer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:flex justify-around min-h-[100vh] dark:bg-[#000] dark:text-[#d4d6d6]">
        <div>
          <Logo className="hidden sm:flex" />
          <Sidebar className="flex-1" />
        </div>
        <div>
          <Header />
        </div>
        {/* <Sidebar /> */}
        {/* <Sidebar /> */}
      </div>
    </div>
  );
}
